### ISSUE TITLE
Unexpected consumer behavior

### ISSUE THREAD

**Issue by doranych** [cheshir/go-mq#35]
Consumers consume messages without explicit call of Consumer.Consume method. 

i.e. 
we have 2 binaries one with producer, another one with consumer, based on the same code and same config. 
1. run producer (without consuming) 
2. run consumer
3. produce several messaged to amqp server
4. consumer consumes several messages
5. stop producer
6. consumer gets messages from nowhere (ofc we produced them before, they just stacked in non existent  consumer in producer binary)

In my case, Rabbit shows us 2 consumers.

Following [this](https://github.com/cheshir/go-mq/blob/0d00eb3ad0fa3363388c2d27e353c3941553fa20/mq.go#L377) messages are not suppose to be consumed without real Consumer.Consume call

If you may guide where should i dig, i might be able to fix this

**Comment by cheshir** [comment]
@doranych 
Hi!

I'm not sure I understand what is the problem.
Can you provide minimal code that will reproduce this behaviour?

It's ok that consumer continue consuming messages from the queue even if producer has been stopped. But I believe you're talking about something else.

**Comment by doranych** [comment]
@cheshir 
Good morning!

[Here it is](https://gist.github.com/doranych/4254989190c95d0dc4cb13f75b05602a)
Compile and run app
Open your rabbitmq web interface to analyze things happening. 
1. Your queue will have 10 messages in total. And 10 of them in unacked state. 
2. kill producer
3. messages will move to ready state

Messages suppose to be in ready sate when they are published.  
Messages will be transferred to unacked state when consumer get message.
Messages will be transferred to ready or removed from queue when consume release them (in any way)

all the above things show us this situation: 
1. producer produces messages (that's nice)
2. message publish to queue
3. message popped from queue to consumer...

Wait. We haven't started consumer!
That is the thing i'm talking about.

**Comment by cheshir** [comment]
@doranych morning!

I get it. There is two points:

When you described consumer in the config it will be created and registered in rabbit. But you will not get messages until you specified consumer handler. It's supposed that if you configure app with consumer so you're going to use it. 🙂

That's why you see consumers in the rabbit management panel.

The next problem is ack/ready states. 

From [prefetch policy](https://www.rabbitmq.com/consumer-prefetch.html) documentation: `A value of [prefetch_count] 0 is treated as infinite, allowing any number of unacknowledged messages.`

In your example rabbit will deliver all messages to the registered consumer but it will not process them because there is no started workers.

Is there anything else that I can help you with?

**Comment by doranych** [comment]
Well, seems, that i misunderstood behavior pattern and it works the way it suppose to work. 
Thx for clarifying this for me
